### ISSUE TITLE
QuickStart TEST API key not working

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-application-modules#145]
Reported by several users on the oba-dev list:
https://groups.google.com/forum/#!topic/onebusaway-developers/IToYormLGWA

I haven't had a chance to try and reproduce.

In the QuickStart documentation we definitely say that this should work:
https://github.com/OneBusAway/onebusaway-application-modules/wiki/OneBusAway-Quickstart-Guide

**Comment by nkiermaier** [comment]
The issue is that the key given in the quickstart is incorrect.  

The key given in the quickstart is ?key=TEST.

However, the default pre-existing key in a fresh OBA deployment is ?key=web.

So the docs need might need updating?

IMO it would be better to demonstrate clearly how to access the admin interface to add/remove web keys rather than just have a default key setup. 

I had to kind of dig around to figure this out.

**Comment by kurtraschke** [comment]
@barbeau So, this _should_ work, but after a little poking around it's not yet clear to me why it's broken.  

First, in [`KeyValidationServiceImpl`](https://github.com/OneBusAway/onebusaway-application-modules/blob/master/onebusaway-users/src/main/java/org/onebusaway/users/impl/validation/KeyValidationServiceImpl.java), there are several API keys hard-coded (and `TEST` is one of them).  The `isValidKey` method in that class is coded such that if the key is one of the hard-coded keys, then the user database is bypassed entirely.  Just to be sure there isn't some Spring component magic happening here, there are no other implementations of `KeyValidationService` in the codebase—and in fact `KeyValidationServiceImpl` gets [explicitly wired up](https://github.com/OneBusAway/onebusaway-application-modules/blob/master/onebusaway-api-webapp/src/main/default-resources/data-sources.xml) in `data-sources.xml`.

Anyway, at least in the quickstart, none of the hard-coded keys work—so that's one unexplained behavior.

Then, the [`data-sources.xml`](https://github.com/OneBusAway/onebusaway-application-modules/blob/master/onebusaway-quickstart/onebusaway-quickstart-assembly/src/main/assembly/onebusaway-quickstart-api-webapp/WEB-INF/classes/data-sources.xml) for the API webapp which is embedded in the quickstart contains this:

```
<bean class="org.onebusaway.users.impl.CreateApiKeyAction">
  <property name="key" value="TEST"/>
</bean>
```

Unlike the hardcoded keys in `KeyValidationServiceImpl`, this should result in the API key being added to the user database by [`CreateApiKeyAction`](https://github.com/OneBusAway/onebusaway-application-modules/blob/master/onebusaway-users/src/main/java/org/onebusaway/users/impl/CreateApiKeyAction.java).

Oddly, when `CreateApiKeyAction` is [invoked](https://github.com/OneBusAway/onebusaway-application-modules/blob/master/onebusaway-webapp/src/main/resources/org/onebusaway/webapp/application-context-webapp.xml) by `onebusaway-webapp`, it succeeds—this is how the `web` key gets created: 

```
INSERT INTO OBA_USER_INDICES VALUES('api','web','web',2)
INSERT INTO OBA_USER_INDICES VALUES('username','admin','v1|2Q//uYLjOtPWAd3lQhvAXNvZfy0hz81SQhswvM3WHBg=',1)
INSERT INTO OBA_USER_ROLES VALUES('ROLE_ADMINISTRATOR')
INSERT INTO OBA_USER_ROLES VALUES('ROLE_ANONYMOUS')
INSERT INTO OBA_USER_ROLES VALUES('ROLE_USER')
INSERT INTO OBA_USER_ROLES_MAPPING VALUES(1,'ROLE_ADMINISTRATOR')
INSERT INTO OBA_USER_ROLES_MAPPING VALUES(1,'ROLE_USER')
INSERT INTO OBA_USER_ROLES_MAPPING VALUES(2,'ROLE_USER')
INSERT INTO OBA_USERS VALUES(1,'2015-09-04 20:55:44.356000','2015-09-04 21:00:05.158000','...,'1')
INSERT INTO OBA_USERS VALUES(2,'2015-09-04 20:55:50.630000',NULL,'...','1')
```

**Comment by kurtraschke** [comment]
So, my prior analysis was wrong, and...wrong.  `KeyValidationServiceImpl` and a number of related classes appear to be dead code; that was a complete dead-end.

The second semi-dead-end was the `data-sources.xml` file in the `onebusaway-quickstart-api-webapp` directory.  Somehow I'd convinced myself that this was the `data-sources.xml` file used by the API servlet in the quickstart, which it isn't (at least, not exactly).

Recall that there are two builds of the quickstart, one with both the API servlet and the webapp servlet (this has the Maven qualifier `webapp`), and one with only the API servlet (this has the Maven qualifier `api-webapp`).

In either build, there's actually only one Java servlet being deployed, because the quickstart is a wrapper around `onebusaway-combined-webapp` (an assembly which merges `onebusaway-transit-data-federation-webapp`, `onebusaway-api-webapp`, and `onebusaway-webapp`)—**thus only one `data-sources.xml`**.  This was where I'd gone wrong before, thinking that there was one `data-sources.xml` for each servlet, which isn't the case, because there's only one servlet.

So, the real bug here is that the `data-sources.xml` for the API+webapp build of the quickstart lacks the calls to `CreateApiKeyAction` that the `data-sources.xml` for the API-only build contains.

**Comment by kurtraschke** [comment]
@nkiermaier, this should now be resolved in the latest snapshot build: http://nexus.onebusaway.org/service/local/artifact/maven/content?r=public&g=org.onebusaway&a=onebusaway-quickstart-assembly&c=webapp&e=war&v=1.1.14-SNAPSHOT

**Comment by barbeau** [comment]
@kurtraschke and @sheldonabrown might be worth cutting a new release for this - thoughts?

**Comment by kurtraschke** [comment]
If we're contemplating a release, it might also be worthwhile to release [`onebusaway`](https://github.com/onebusaway/onebusaway) (the parent POM), in particular so that we can pull in the fix for [this bug](https://issues.apache.org/jira/browse/MSITE-682) in `maven-site-plugin` which results in apostrophes and quotes being stripped from the output.

**Comment by sheldonabrown** [comment]
@kurtraschke cleaning up some old pull requests and issues.  I've bumped the maven-site-plugin as you requested.

**Comment by nkiermaier** [comment]
@kurtraschke  Thank you sir.
