### ISSUE TITLE
Load data from mysql

### ISSUE THREAD

**Issue by pcalderoncity** [OneBusAway/onebusaway-application-modules#218]
I have tried to configure mysql as datasource but when i deploy the onewaybus-webapp and I excute this test (http://localhost:8081/onebusaway-api-webapp/api/where/agencies-with-coverage.xml?key=TEST)  does not happen anything. 
With HSQLDB I have no problem. 

The Mysql database has the same data that my gtfs bundle.
I have changed both datasources in webapp and federationwebapp.
Exploring the code, apparently, is the onebusaway-transit-data-federation module who process the request and it needs a FederatedTransitDataBundle bean.

¿Is it possible change the configuration for the module can read the data from mysql DB?

Any help would be greatly appreciated.

**Comment by barbeau** [comment]
Have you looked at the following?

* https://github.com/OneBusAway/onebusaway-application-modules/wiki/Developer-Guide#choosing-a-database
* https://github.com/OneBusAway/onebusaway-application-modules/wiki/Database-Guide

What version of OBA are you using?

**Comment by pcalderoncity** [comment]
Thanks for your answer.

Yes i have followed the instructions twice. I think I am doing something wrong.

I am using the version 1.1.18. 
I think my proble is in the application-context-common.xml file configutration from onebusaway-transit-data-federation module.

**Comment by barbeau** [comment]
You shouldn't have to touch application-context-common.xml. Only changes needed from HSQLDB to MySQL should be changing data-sources.xml in oba-transit-data-federation-webapp.

Could you post censored versions of your data-source.xmls?

**Comment by sheldonabrown** [comment]
Yes, and post any exceptions in the logs as well.

**Comment by sheldonabrown** [comment]
It may be worthwhile to take a step back and discuss why you don't want to
use a bundle.  In recent history the bundle is the preferred/supported way
to load data.  You are making a bunch of extra work for yourself, and are
in completely unsupported territory, by not using a bundle.

But with that said, the error you are facing is you need to define
bundlePath, regardless if you are using it or not, as there are other
references to it.

A fragment like this in your data-sources.xml will at least get you past
that specific error:

<bean class="org.onebusaway.container.spring.SystemPropertyOverrideConfigurer">
  <property name="order" value="-2" />
  <property name="properties">
      <props>
          <prop key="bundlePath">/var/lib/obanyc/no-such-dir</prop>
     </props>
  </property>
</bean>

**Comment by barbeau** [comment]
@pcalderoncity to expand on what @sheldonabrown said - in the normal OBA server setup, you have both a bundle (optimized and serialized data structures used in the code) and a database.  In the default QuickStart configuration, the database used in HSQLDB.  You can easily configure the server to use MySQL instead of HSQLDB, but you'll still need to have a bundle built from the GTFS data.  On startup the OBA server reads the bundle and caches some info in the database - the database also holds other info like API keys, etc.

As @sheldonabrown says, there really isn't a good reason that I'm aware of for not using the bundle.  So if you want the easiest setup, configure the bundle the same way as you did for HSQLDB, and just change the database config to use MySQL instead of HSQLDB.

**Comment by barbeau** [comment]
Since this issue tracker is used for bug reports, and this seems more of a question of getting a usual configuration up and running, I'm going to close it out.

@pcalderoncity Feel free to comment further here if you'd like, but generally these types of config questions are better posted to https://groups.google.com/forum/#!forum/onebusaway-developers.

**Comment by barbeau** [comment]
Continued at https://groups.google.com/forum/#!topic/onebusaway-developers/iA3oeICdfao...
